api:
  dashboard: true
  insecure: true  # Enable insecure API for direct IP access on port 8080

log:
  level: DEBUG # Set to DEBUG to see logs

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "tcp://socat:2375"
    exposedByDefault: false
    network: shared-network
  file:
    directory: /traefik-auth
    watch: true

ping:
  entryPoint: web
